spring:
  profiles:
    include: dev, jwt
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
jwt:
  secret: youcantrevealthesecretkey1234012300040
