server:
  port: 9090
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/graduate
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      hbm2ddl.auto: create
      format_sql: true
    show-sql: true
    open-in-view: false
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
cloud:
  aws:
    credentials:
      accessKey: {access key}
      secretKey: {access secret key}
    s3:
      bucket: smu-graduation-bucket
    region:
      static: ap-northeast-2
    tack:
      auto: false
