server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://220.149.31.104:3306/graduate?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      validation-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties.hibernate:
      format_sql: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB